### ISSUE TITLE
Upgrade boto3 health SDK version

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/external-domain-broker-migrator#168]
AWS is alerting cloud.gov that we are using deprecated versions of boto3 health SDK and need to above versions `1.27.1`  to work.  As of Feb'24 version `1.34.34` is the most recent version.

## Notes

- Validate that recent versions don't introduce new issues/bugs

## Acceptance Criteria

- [x] Determine code changes needed for the upgrade
- [x] Throughly test in lower environments
- [x] If a test suite does not exist in the repo - create on to validate new versions of `boto3` in the future

**Comment by rcgottlieb** [comment]
Updated Boto3 version to latest and other supporting packages
Updated the pip-tools package and piptools version
Updated both runtime and pyproject to use Python 3.x
Updated Dockerfile to use Python 3.9
Updated pipeline to use appropriate slack channels for success and failure
