### ISSUE TITLE
Creates bare instance

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/external-domain-broker-migrator#45]
The migrator needs to create an instance of the new plan before doing the rest of the migration

**Comment by ccostino** [comment]
@bengerman13 this issue corresponds to steps 1 and 2 in the plan, correct?

1. Enable the external-domain-service migration plan in the service instance's space. This plan is a special plan used only for this purpose.
1. Create an instance of the migration plan in the space.

**Comment by bengerman13** [comment]
Step one is already done (it was #44 / #55 ) - this is just about step 2

**Comment by ccostino** [comment]
PR is live! https://github.com/cloud-gov/external-domain-broker-migrator/pull/64
