### ISSUE TITLE
Migrator updates from migration plan to cdn plan 

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/external-domain-broker-migrator#46]
The migrator should call update-service to update the service from the bare plan to the cdn plan

**Comment by ccostino** [comment]
This looks like steps 5 - 7, but want to confirm:

1. Call update-service on the new instance so CAPI knows about the plan change.
2. Call purge-service on the old service instance, so CAPI knows it's gone, but the cdn-broker doesn't delete the cloudfront distribution
3. Mark the instance as inactive in the cdn-broker database so the cdn-broker doesn't try to renew its certificate

**Comment by bengerman13** [comment]
This was written to just be 5 - we should have more tickets for 6 & 7

**Comment by ccostino** [comment]
@bengerman13 this is to update the bare migrator plan to the new, external domain broker plan that will replace the old CDN instance and plan, correct?

**Comment by bengerman13** [comment]
This is calling update on the service instance to convert it from a migrator plan to a cdn instance, yes

**Comment by bengerman13** [comment]
@ccostino this should consist of two things:
- serialize update params to JSON, as [expected by the external domain broker](https://github.com/cloud-gov/external-domain-broker/blob/main/broker/api.py#L435)
- call [update on the service_instance](https://github.com/cloudfoundry-community/cf-python-client/blob/master/main/cloudfoundry_client/v2/service_instances.py#L30)

**Comment by ccostino** [comment]
A draft PR is in place for this: https://github.com/cloud-gov/external-domain-broker-migrator/pull/66

I think I'm getting close, but need to figure out how best to test this and how to properly set the tests up.

**Comment by ccostino** [comment]
@bengerman13, @onelittlebecca, and I had a discussion this morning about some additional error handling to make sure we have visibility into anything that goes wrong and how migrations are proceeding once this runs.  We should be able to achieve this with [`sys.excepthook`](https://docs.python.org/3/library/sys.html#sys.excepthook), like so:

```python
def our_excepthook(type, value, traceback):
    sys.__excepthook__(type, value, traceback)
    send_summary_email_if_available()
    send_exception_email(type, value, traceback)
```

PR feedback continues, but getting closer as well!  Looks a slight adjustment to one of the underlying `cf` client calls and adding a bit more test coverage at this point.

**Comment by bengerman13** [comment]
☝️ that should be a new ticket, so I made one :) #70

**Comment by ccostino** [comment]
Excellent call, sir! :-)
